### ISSUE TITLE
Not possible for user to react on errors after initial connection

### ISSUE THREAD

**Issue by bonan** [hemtjanst/bibliotek#12]
The current implementation is a fire and forget call to `mqtt.New()` (if first connection attempt is successful). Future connection errors cannot be forwarded to the user

It is currently not possible for the user wants to react to future errors. This limits the possibility to implement a fail-fast scenario, or to add custom logging of connect errors.

I suggest adding a new method, `Start(context.Context) error`, which will block until any disconnecting error is received.

If we care about backwards compatibility - this could be solved by instead adding a `New2(*Config) (MQTT, error)` function (with a better name) to allow easier migration

**Comment by daenney** [comment]
Backwards compatibility isn't much of a concern here, we're still in the v0.y.z range of releases. Given that everything builds using Go modules it's easily handled too.

**Comment by daenney** [comment]
Give backwards compatibility isn't much of a concern, why not change the `New()` method to do what you're suggesting `Start()` should do? Or toss `New()` out the window and only have `Start()`?

**Comment by bonan** [comment]
Fixed in v0.6.0 by #13
